version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.be
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://user:password@db/musics_db
    depends_on:
      - db

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.fe
    ports:
      - "3000:80"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: musics_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
