version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.be
    ports:
      - "5000:5000"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=greeting_app
      - MYSQL_HOST=db
    depends_on:
      - db

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.fe
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: greeting_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
