CREATE DATABASE IF NOT EXISTS greeting_app;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'user_password';
GRANT ALL PRIVILEGES ON greeting_app.* TO 'user'@'%';
FLUSH PRIVILEGES;

USE greeting_app;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
