name: Build Docker Images
run-name: Build Docker Images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  docker_build_push_oz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4
      - name: Login to DockerHub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d #v3
        with:
          # https://github.com/afshin-deriv/MagicMusic/settings/secrets/actions
          # Create new secret DOCKER_USERNAME & DOCKER_PASSWORD 
          # Filled by Docker hub user/pass https://hub.docker.com/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build BE
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 #v4
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/magicmusic-be:${{ github.ref_name }}
          no-cache: true
      - name: Build BE
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 #v4
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          # name 
          tags: ${{ secrets.DOCKER_USERNAME }}/magicmusic-fe:${{ github.ref_name }}
          no-cache: true
