name: Build Docker Images
run-name: Build Docker Images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
    build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4

      - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $latest_tag"
          echo "VERSION=${latest_tag:-v0.0.0}" >> $GITHUB_ENV
        
      - name: Increment version
        id: increment_version
        run: |
          version=$(echo "${{ env.VERSION }}" | sed 's/v//')
          IFS='.' read -r -a version_parts <<< "$version"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}
          new_patch=$((patch + 1))
          new_version="v${major}.${minor}.${new_patch}"
          echo "New version: $new_version"
          echo "VERSION=$new_version" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d #v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build BE
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 #v4
        with:
          context: .
          file: Dockerfile.be
          push: true
          # tags: ${{ secrets.DOCKER_USERNAME }}/magicmusic-be:${{ github.ref_name }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/magicmusic-be:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/magicmusic-be:latest
          no-cache: true

      - name: Build FE
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 #v4
        with:
          context: .
          file: Dockerfile.fe
          push: true
          # tags: ${{ secrets.DOCKER_USERNAME }}/magicmusic-fe:${{ github.ref_name }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/magicmusic-fe:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/magicmusic-fe:latest
          no-cache: true
