name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install flake8 pytest coverage

      # - name: Lint code
      #   run: |
      #     flake8 .

      # - name: Run tests with coverage
      #   run: |
      #     coverage run -m pytest
      #     coverage report
      #     coverage xml

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     file: ./coverage.xml

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Debug - Print working directory
        run: pwd

      - name: Debug - List root directory contents
        run: ls -la

      - name: Debug - List frontend directory contents
        run: ls -la frontend

      - name: Install Node.js dependencies
        working-directory: frontend
        run: npm install

      # - name: Run Node.js tests with coverage
      #   working-directory: magicmusic/frontend
      #   run: |
      #     npm run test -- --coverage --reporters=jest-junit

      # - name: Upload Node.js coverage to Codecov
      #   working-directory: magicmusic/frontend
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: ./coverage/jest/lcov-report/*.html

      # export PYTHONPATH=./ 
