name: CI


on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main


jobs:
  ci:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.9'


      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r backend/requirements.txt
      #     pip install flake8 pytest coverage


      # - name: Lint code
      #   run: |
      #     flake8 .

      # - name: Run Python tests with coverage
      #   env:
      #     PYTHONPATH: ./backend
      #     DATABASE_URI:  sqlite:///:memory
      #   run: |
      #     coverage run -m pytest
      #     coverage report
      #     coverage xml -o backend/coverage.xml

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: frontend
        run: npm install
      - name: Test and coverage
        working-directory: frontend
        run: npm run test -- --coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}


      # export PYTHONPATH=./
